### ISSUE TITLE
still cant open

### ISSUE THREAD

**Issue by zhaishengfu** [vritvij/Project-Ignite#3]
sorry about that， but when i open using 4.15.1， it says“World.umap is asset file" and cant load the map. When I enter , nothing can be loaded . what's the matter?

**Comment by vritvij** [comment]
Are you using "git clone" or "Download Zip"? Since I'm using Git LFS, the "download zip" won't work. You will have to use git clone and make sure that you have GIT LFS installed.

**Comment by zhaishengfu** [comment]
oh, I use Download. ok, I will try git clone

**Comment by vritvij** [comment]
Let me know how it goes.

**Comment by zhaishengfu** [comment]
Sorry, But still has problem. i git lfs clone several times and at last it will tell me:
nic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x7070dc]
I used Gui for Windows. What is the problem?

**Comment by vritvij** [comment]
That's weird. I tried it on 2 different PC's using Git clone in the terminal and it worked perfectly.

**Comment by zhaishengfu** [comment]
I am lways interruptted in the middle process. Now I am trying git lfs pull to restart it

**Comment by vritvij** [comment]
I don't know why that is happening on your PC. But it's working perfectly on mine. I just tried the git lfs clone in the terminal and the game downloaded and works perfectly

**Comment by zhaishengfu** [comment]
Indeel now I can Open your game and it's logic is ok.

**Comment by vritvij** [comment]
Perfect!

**Comment by zhaishengfu** [comment]
I tried several times and now I can download almost the project except for one file. I wonder if you could give some introduction or documents about your projects. for example, I am curious about your:
1. how your **procedural** works
2. how the **"data-driven"** works
Thanks!(really wonderful projects, good contribution!)

**Comment by vritvij** [comment]
Well, I've modeled the stat system based on the Pokemon games, i.e I'm storing the base stat values for each creature like health, attack, defense, special attack, special defense, speed, base experience yield, catch rate, growth rate etc in data tables and use a mathematical formula to scale the values according to the creatures current level. 

Moreover, the nature and gender of the creature are also generated at run time based on a random number generator and predefined thresholds. Both these aforementioned properties affect their stats and how the creature will interact with the player. e.g. if the creature is of "Brave" nature then it will actively seek a battle, if the creature is "sassy" then it will try to hide behind cover, if the creature is "Timid" then it will try to run away from you as far as possible, if the creature is "Docile", it will ignore your presence, if the creature is "Serious", it will be wary of your presence and attack you only if you get too close. There are 25 different natures that are mapped to the above 5 behaviors.

So that's where the game's "data-driven" and "procedural" tags come from. As for the documentation, any other particular area of interest? 

BTW, could you let me know which project file is not being downloaded?

**Comment by zhaishengfu** [comment]
Ok， Thank you very much . I am clear!( Now I know why some creatures attack me and why some don't respond). Datatable is really good methods for data-driven. Maybe I will dive into your methods later.
As for the missing file, Sorry, I also don't know . When i use "git lfs pull", it only shows missing one flle, but don't show me which one.
